---
format:
  pdf:
    documentclass: article
    geometry:
      - top=20mm
      - left=20mm
      - right=20mm
      - bottom=20mm
    fontsize: '12'
---

\begin{flushright}
Sophia Heinrich \\
Lincoln, NE \\
heinrichs6739@gmail.com
\end{flushright}

\vspace{1em}

\today

\vspace{1em}

Garmin \\ 1200 East 151st Street, Olathe, Kansas 66062, United States

\vspace{1em}

Dear Garmin,

In the internships I worked over the past summers, I found the ones that kept me the most intellectually
stimulated and challenged were the ones I loved most. While I have always heard great reviews about
Garmin's environment and culture from past employees, it wasn't until I spoke to your representatives at the
Raikes School Career Fair that I could see the position of Software Engineer would be a position
that could satisfy my need for challenging work in a fast-paced environment where I can grow as an engineer and be
supported by my peers and mentors. Based on my love for problem-solving and learning, and my experience
working and communicating on software teams, I believe I would be an asset to Garmin and would thrive in an agile environment and show passion for the work I do with my team.

During my four years at the University of Nebraska - Lincoln, I've had multiple experiences that have contributed to building both hard and soft skills that would make me a valuable asset to Garmin, especially in your Full Stack (Java/Angular) position. As an intern for Hudl, I learned how to communicate and work with on an eight-person software engineering team where we built customer-centered software products by collaborating and problem-solving on a daily basis. As Software Engineering interns, we were given the same responsibilities as a full-time software engineer where we participated in agile Scrum ceremonies, collaborated on assigned tickets, and ultimately shipped features built to satisfy the pains of our users. Especially in my first summer internship, web development was not a topic traditionally taught to first-year computer science students, so I had to quickly learn and become comfortable with new repository structures and coding languages as tasks were assigned to me. When posed with a
problem, I would work with my mentor or other engineers to adapt and quickly come up with strategic solutions to
roadblocks in a task's progress.At the end of the internship, I had shipped several new features out to users. I enjoyed my time as a software engineering intern because it gave me a way to
stay intellectually curious over the summer and grew my skills as not only an engineer, but also a learner, communicator, and problem-solver.

After my first experience with web development, I wanted to continue to grow my skills throughout the school year. Therefore, I decided to join a new, educational startup, TeachFront, founded by one of my computer science professors. In my primary role as a Frontend Software Developer, I collaborated on a team of 4 students and our professor to develop our web application in React/Typescript. Through my time on the startup, I not only grew my development skills, but I also learned the importance of listening to your customers. Throughout tons of user interviews, we often discovered that the designs and features \textit{we} thought were most useful, were actually much lower priority or weren't helpful at all. Additionally, given that our product was intended to be used in the classroom, I learned a lot about the importance of building accessible software that complies with the required standards. This dedication to building high-quality, inclusive software contributed to TeachFront securing over $110,000 in earnings, validating our team's ability to deliver a product that truly served our educational community.

With my life-long love for learning and problem-solving, and my recently-gained experience in software engineering, I believe I would be a strong Software Engineer for Garmin I look forward to further
discussing my qualifications for this position with the Garmin Team. If you would like to arrange a meeting,
please contact me at 402-617-2141 or heinrichs6739@gmail.com. 

Thank you for your time and consideration.

\vspace{1em}

Sincerely,

\vspace{2em}

Sophia Heinrich
