---
format: 
  pdf: 
    documentclass: article
    geometry:
      - top=10mm
      - left=15mm
      - right=15mm
      - bottom=5mm
      - heightrounded
    fontfamily: libertine
    colorlinks: true
    fontsize: 30pt
    include-in-header: 
      text: |
        \usepackage{multicol}
        \usepackage{lipsum}
        \usepackage{hyperref}
        \usepackage{libertine}
        \usepackage{enumitem}
        \setlist[itemize]{leftmargin=1em, labelsep=0.5em, noitemsep, topsep=0pt}
        \pagestyle{empty}
        \setlength{\multicolsep}{2pt plus 1.0pt minus 0.75pt}% 50% of original values
        \setlength{\columnsep}{3em}
---
\begin{huge}\begin{center}{\bf Sophia Heinrich}\end{center}\end{huge}
\vspace{-0.75cm}
\begin{center}(402) 617-2141 ∙ heinrichs6739@gmail.com ∙
\href{https://www.linkedin.com/in/sophia-heinrich-unl/}{LinkedIn}
\end{center}

\vspace{-0.25cm}
\begin{large}
  {\bf EDUCATION}
  \vspace{3pt}
  \hrule

\noindent \textbf{University of Nebraska-Lincoln \hfill Lincoln, NE} 
\newline
\textit{BS in Computer Science, Mathematics, Data Science, Minor in Business (GPA: 4.0)} \hfill May 2026
\end{large}
\vspace{-0.1cm}

* \textbf{Jeffrey S. Raikes School of Computer Science and Management:} A highly selective honors program focusing on the intersection of computer science and business management, with emphasis on leadership and communication

\vspace{8pt}

\begin{large}{\bf SKILLS}
  \vspace{3pt}
  \hrule
\end{large}
**Languages and Tools:** Java, TypeScript, React, C# .NET Core, Python, HTML/CSS, SQL, GraphQL, Git, Jest

\vspace{10pt}

\begin{large}{\bf EXPERIENCE}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf Hudl}\end{flushleft}
    \begin{flushright}May 2023 - Aug 2023, May 2025 - Aug 2025\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Software Engineering Intern}\end{flushleft}
    \begin{flushright}Lincoln, NE\end{flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}

* Built **React/Typescript** frontend code across 14 microservices, broadening Hudl’s reach to all high school sports
* Delivered features with a team of 8 developers, designers, and product managers using agile **Scrum** methodologies
* Leveraged **MongoDB** to store and query large-scale sports data and **GraphQL** for retrieval and server-side requests
* Overhauled the school/team profile page on Hudl’s Fan platform, enhancing navigation for **8M+** registered users via breadcrumbs, gradient team-color backgrounds, and containerized content layout
* Optimized American Football autogenerated highlights by redefining the algorithm’s selection of “exciting” clips in **C# .NET**, increasing the engagement and relevance of **11M+** highlights
* Introduced drag-and-drop reordering functionality, enabling coaches to manage playlists and support their athletes
* Created new hotkeys functionality and popover menu, enabling coaches to efficiently navigate and analyze film

\vspace{7pt}

\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\textbf{TeachFront} - (teachfront.com)}\end{flushleft}
    \begin{flushright}Aug 2023 - Aug 2025\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Co-Founder \& Frontend Software Engineer}\end{flushleft}
    \begin{flushright}Lincoln, NE\end{flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* Collaborated with 4 students and a Professor of Practice to develop TeachFront using **React/Typescript** and **C# .NET**
* Utilized agile **Scrum** methodologies with 2-week sprints for efficient project management and timely development
* Produced a feature for instructors to predefine and reuse comments for assessments, including drag-and-drop reorder
* Engineered an announcements and messaging system with nested replies, strengthening instructor–student interaction
* Implemented **WCAG 2.1 AA** accessibility standards, meeting compliance requirements for university adoption
* Secured **$110,333** in total earnings for TeachFront, contributing to the company’s financial strength and future success

\vspace{7pt}

\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf Wells Fargo}\end{flushleft}
    \begin{flushright}June 2024 - Aug 2024\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Software Engineering Intern}\end{flushleft}
    \begin{flushright}Minneapolis, MN\end{flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* Partnered on a **Kanban**-style research and development team focused on advising Wells Fargo’s use of Workday
* Earned leadership approval to enable 6 Workday **AI features** by developing thorough black-box testing procedures
* Strengthened a **C# .NET Core** template application by improving the security for **5+** HR applications and **10+** teams
* Refactored repository methods to use Data Transfer Objects, preventing exposure of relational **SQL** database entities
* Decoupled service layer from database layer and upheld **Model-View-Controller** architecture and separation of duties

\vspace{7pt}

\begin{large}{\bf INVOLVEMENT}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf Kappa Alpha Theta - Rho}\end{flushleft}
    \begin{flushright}Lincoln, NE\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}{\textit{President}}\end{flushleft}
    \begin{flushright}Dec 2024 - Present\end{flushright}
  \end{multicols}
\end{large}
\vspace{-0.3cm}
* Serve as the chapter’s primary representative, making key decisions and ensuring alignment with Theta’s values
* Oversee a **24-officer** cabinet to ensure efficient chapter operations, fostering leadership growth and collaboration

\begin{large}
 \begin{multicols}{2}
    \begin{flushleft}{\textit{Vice President of Operations}}\end{flushleft}
    \begin{flushright}Dec 2023 - Dec 2024\end{flushright}
  \end{multicols}
\end{large}
\vspace{-0.3cm}
* Coordinated with officers to approve all events and ensured events ran smoothly and safely for all **150+** members
* Led weekly meetings to ensure members are upholding Theta’s ideals and awarded members for their positive impacts

\vspace{7pt}

\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf Jeffrey S. Raikes School}\end{flushleft}
    \begin{flushright}Lincoln, NE\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Student Advisory Board Representative}\end{flushleft}
    \begin{flushright}May 2025 - Present\end{flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* Represent Raikes School students by participating in bi-weekly board meetings to advocate for student needs
* Actualize feedback-driven improvements, enhancing the Raikes School experience with fellow representatives
